### PR TITLE
Performance tracing

### PR DESCRIPTION
**Pull request by stayallive**
This is a rough draft of performance tracing, things I like to implement:

- [x] Automatic transactions
	- [x] Parameterized transaction names
	- [ ] Finish transaction after request (maybe already working because `shutdown` usage)
- [x] Add support for Spotlight
- [x] Create spans for features
	- [x] DB queries
		- [x] ~~Code location~~ (defer until next)
	- [x] HTTP requests
		- [ ] ~~Code location~~ (defer until next)
	- [x] Transient operations
- [x] Create breadcrumbs for features
	- [x] DB queries
	- [x] HTTP requests
	- [x] Transient operations
- [x] Add settings to configure tracing / breadcrumb features that are enabled
- [ ] Add context about request (think conditionals tab in query monitor)
- [ ] Update docs
	- [x] How to enable
	- [ ] Considerations (CLI, `SAVE_QUERIES` and multi-site URL)
	- [ ] Usage of `trace` helper for custom spans

### CODE REVIEW

**Comment by killua99** [comment]
this PR will support https://docs.sentry.io/product/profiling/ ?

**Comment by stayallive** [comment]
Indirectly yes. This implements: https://docs.sentry.io/product/performance/

Which is a prerequisite for profiling.

**Comment by killua99** [comment]
Could we break this PR to don't delay it that much?, if we break it with implementing the base of performance, I could create a PR to add profiling.

To avoid this PR as a blocker since I feel is quite big

**Comment by stayallive** [comment]
Maybe I wasn't too clear. With performance implemented we get access to profiling, no extra work. There is nothing specific for the SDK to do except having a transaction (which this PR implements) from which point profiling can be enabled with a single configuration option so no additional PRs needed. Hence why I said this PR indirectly adds support for profiling 🤘

**Comment by killua99** [comment]
Alright. That point is clear.

I was wondering if you could reduce the scope of this issue to allow the basics of performance being enabled to allow use profiling, before the rest of others issues.

**Comment by stayallive** [comment]
We could. But I feel like the scope is small enough. I want performance to be somewhat usable without profiling (since that requires a php extension to be installed so not an option for many WordPress users) and what is listed in the description is a very small subset of what could be done eventually.

**Comment by killua99** [comment]
How could I help to speed up this PR? If there is any chance of it

**Comment by stayallive** [comment]
This PR is technically already working as is. So if you are able and have a test environment it would be great if you can give it a whirl to see if there are any bugs that I missed.

**Comment by eduwass** [comment]
Giving this a try @stayallive

**Comment by saas786** [comment]
@stayallive, excellent work. While I'm still familiarizing myself with the nuances of Sentry's "Performance" feature, I can confirm that the code is tracking activity in the "Performance" tab. I appreciate your efforts in implementing this feature.

However, I did encounter a few fatal errors involving the code here and similar code:

https://github.com/stayallive/wp-sentry/blob/09e1f9d5e39548abb67fd9c6c40b021c16c29ea2/src/tracing/features/class-wp-sentry-tracing-feature-transients.php#L45

```php
$this->record_transient_operation('put', func_get_args()[2]);
```

Replacing it with:

```php
$args = func_get_args()[2];
$this->record_transient_operation('put', $args);
```

resolved my issues.
I didn't notice any other problems in the code.

---

firefox_Re3GrZogVW

**Comment by stayallive** [comment]
@saas786 sorry for my late reaction. I don't see how you change would fix anything... do you have the exact fatal error message by chance so I can try to reproduce?

**Comment by stayallive** [comment]
Thanks all for helping testing. I am going to release this as it currently stands and iterate on it from there based on feedback. Hope everyone tries it out and please open up issues with feature requests and or to report bugs 🎉

**Comment by saas786** [comment]
@stayallive 

Here is the log of the issue I am referring to:

```
[03-Jul-2024 16:21:14 UTC] PHP Fatal error:  Cannot use result of built-in function in write context in \wp-content\plugins\wp-sentry-integration\src\tracing\features\class-wp-sentry-tracing-feature-transients.php on line 45
```

**Comment by stayallive** [comment]
That interesting, thanks @saas786. I've released https://github.com/stayallive/wp-sentry/releases/tag/v7.17.2 which should fix that 😄

**Pull request merged**
